### ISSUE TITLE
Serial port publish messages to broker, bad performance!

### ISSUE THREAD

**Issue by RadioOperator** [halfbakery/serial2mqtt-openwrt#2]
Hi,   2 issues on the serial port:

1. after install the serial2mqtt and reboot, the Subscribe (broker -> uart) auto-started and work fine.   
    But serial port Publish (uart -> broker) not work automatically.

2. Serial port send out is very unstable,  more 50% lose.

pls help.

**Comment by halfbakery** [comment]
Hi,

Have you connected the device to the on-board serial port (`/dev/ttyS0`) as you stated in https://github.com/halfbakery/serial2mqtt-openwrt/issues/1 ?

Is your on-board serial port working correctly?
* please check https://openwrt.org/docs/techref/hardware/port.serial
* try to test your serial port with `picocom` first. It's a simple terminal emulator program, and you can communicate directly with your device
* please check `/etc/inittab` to see whether the login process (`getty`/`askfirst`/etc) is running and stealing characters

**Comment by RadioOperator** [comment]
hi thanks for quick reply.
my openwrt device has 2 uart ports, one is ttyS0, another ttyUSB0 by FT232, both working good on other cases and same problem on serial2mqtt.  i have released the uart from console output.
i am sure the problem 2 is uart part code, because i can see my uart tx message on web putty console, but sometines 50% the message not transfered to the broker.

**Comment by halfbakery** [comment]
Hi,

Could you test it with the upstream serial2mqtt version running it on a PC or an ARM board? I'd like to know where's the bug is.

**Comment by RadioOperator** [comment]
PC terminal software ~ PC USB ~ CH341 ~ FT232 ~ openwrt ~ wifi ~ test.mosquitto.org ~ wifi ~ PC mqtt client.
That is my setup.

**Comment by RadioOperator** [comment]
At the PC terminal, I use { "cmd":"MQTT-PUB","topic":"dst/AR300M.USB0","message":"12345","qos":0,"retained":false }\n   - jsonArray to test. correct or not?

**Comment by RadioOperator** [comment]
for the problem 1,
serial2mqtt should be auto-started after reboot, beause uart can received messages from broker, all ok.

But why UART cannot send out any messages to broker after reboot? I have to login the console, restart "serial2mqtt" manully, then UART to broker worked. I need it fully automatic work from power-on.

**Comment by halfbakery** [comment]
> At the PC terminal, I use { "cmd":"MQTT-PUB","topic":"dst/AR300M.USB0","message":"12345","qos":0,"retained":false }\n - jsonArray to test. correct or not?

It seems legit, but it's a `jsonObject` (and not  a `jsonArray`) (see the `serial` / `protocol` option). The `jsonArray` format is an array without any field names, e.g.:
```
[1,"dst/AR300M.USB0","12345",0,false]\n
```

**Comment by halfbakery** [comment]
Maybe this could have been your previous (#1) problem: `serial2mqtt` reads its configuration file `serial2mqtt.json` from the current directory. That's why I had given the `/etc/serial2mqtt/serial2mqtt.json` as a command line argument in the init script. My guess is that serial2mqtt uses different configuration upon startup or started from the command line.

**Comment by RadioOperator** [comment]
> > At the PC terminal, I use { "cmd":"MQTT-PUB","topic":"dst/AR300M.USB0","message":"12345","qos":0,"retained":false }\n - jsonArray to test. correct or not?
> 
> It seems legit, but it's a `jsonObject` (and not a `jsonArray`) (see the `serial` / `protocol` option). The `jsonArray` format is an array without any field names, e.g.:
> 
> ```
> [1,"dst/AR300M.USB0","12345",0,false]\n
> ```

Hi, tested. This jsonObject format is all OK, my problem 1 and 2 seems solved. thanks.

In my serial2mqtt.json config file, original protocol option is `jsonArray` , in Serial2Mqtt.cpp default setting is `jsonObject`, so I use `jsonArray` in my test. 
You right, serial2mqtt cannot load the serial2mqtt.json config file correctly in initial stage, so I change the UART from ttyUSB0 to ttyS0 is no effective, I have to modify the Serial2Mqtt.cpp for ttyS0, this part should improve in future.

**Comment by RadioOperator** [comment]
serial2mqtt receives the uart input is reliable, but response time is unstable, I got 1~8 seconds time delay, so sad.

**Comment by halfbakery** [comment]
Try to give the name of the config file as a command line argument, it should help. The init script does exactly this. It works perfectly for me on my openwrt router.



> serial2mqtt receives the uart input is reliable, but response time is unstable, I got 1~8 seconds time delay, so sad.

8 seconds delay is definetly huge. Try to enable debugging from the configuration file and start serial2mqtt from the command line to see what happens. 

https://github.com/vortex314/serial2mqtt/blob/master/doc/CONFIGURATION.md#the-log-group
https://github.com/vortex314/serial2mqtt#update-30-dec-2020--added-colorcoding-log-of-protocol-and-arduino-debug-output

**Comment by RadioOperator** [comment]
Hi,
Still have the following problems on the code:

1. After I switched the uart port to ttyS0 (modified `main.cpp` and `serial2mqtt.json` 2 files only), ttyS0 got a bug - received two input strings, transfer to the broker only one string. I have to find what happened. (ttyUSB0 is ok.)

2. uart response time is unstable, 1-8s, both ttyUSB0 and ttyS0.
thanks.

**Comment by RadioOperator** [comment]
> Hi,
> Still have the following problems on the code:
> 
> 1. After I switched the uart port to ttyS0 (modified `main.cpp` and `serial2mqtt.json` 2 files only), ttyS0 got a bug - received two input strings, transfer to the broker only one string. I have to find what happened. (ttyUSB0 is ok.)
> 2. uart response time is unstable, 1-8s, both ttyUSB0 and ttyS0.
>    thanks.

Sorry, there is no such problems in the code, hardware problem, my uart ttyS0 Rx line with interferencs.
Thanks.
