### ISSUE TITLE
luci-app-serial2mqtt template created

### ISSUE THREAD

**Issue by RadioOperator** [halfbakery/serial2mqtt-openwrt#3]
Hi, @halfbakery
I've created a template for serial2mqtt-openwrt, please check my repo [luci-app-serial2mqtt](https://github.com/RadioOperator/luci-app-serial2mqtt).

I tried to use UCI API in serial2mqtt, got many issues. because my less experience on linux/openwrt/c++, hope you or someone could help. Thnaks.

**Comment by RadioOperator** [comment]
no further actions.

**Comment by halfbakery** [comment]
Hi,

Sorry for the late reply, I had no time in the last months. Your app looks promising!

IMHO the simplest and fastest method is to generate `serial2mqtt.json` from your config upon boot, and put the generated config under `/var/run`. This approach is the same as UCI had chosen to generate `/var/run/hostapd-phy0.conf` from `/etc/config/wireless`.
