### ISSUE TITLE
Undefined reference to `Proxy_connect`

### ISSUE THREAD

**Issue by r32190** [halfbakery/serial2mqtt-openwrt#5]
Thanks for the effort making this project. I have encountered compilation error using docker:

---------------------------------
/home/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make -C /home/build/openwrt/build_dir/target-mipsel_24kc_musl/serial2mqtt-0.0/serial2mqtt -f serial2mqtt.mk CXX=mipsel-openwrt-linux-musl-g++ LinkerName=mipsel-openwrt-linux-musl-g++
make[3]: Entering directory '/home/build/openwrt/build_dir/target-mipsel_24kc_musl/serial2mqtt-0.0/serial2mqtt'
mipsel-openwrt-linux-musl-g++ -o ./Debug/serial2mqtt @"serial2mqtt.txt" -L. -L../Common/Debug -L../paho.mqtt.c/build/output  -lCommon -lpthread  -l:libpaho-mqtt3c.a
/home/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: ../paho.mqtt.c/build/output/libpaho-mqtt3c.a(MQTTAsyncUtils.o): in function `MQTTAsync_connecting':
/home/build/openwrt/build_dir/target-mipsel_24kc_musl/serial2mqtt-0.0/paho.mqtt.c/src/MQTTAsyncUtils.c:2819: undefined reference to `Proxy_connect'
/home/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /home/build/openwrt/build_dir/target-mipsel_24kc_musl/serial2mqtt-0.0/paho.mqtt.c/src/MQTTAsyncUtils.c:2819: undefined reference to `Proxy_connect'
/home/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: ../paho.mqtt.c/build/output/libpaho-mqtt3c.a(MQTTProtocolOut.o): in function `MQTTProtocol_connect':
/home/build/openwrt/build_dir/target-mipsel_24kc_musl/serial2mqtt-0.0/paho.mqtt.c/src/MQTTProtocolOut.c:332: undefined reference to `Proxy_connect'
/home/build/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /home/build/openwrt/build_dir/target-mipsel_24kc_musl/serial2mqtt-0.0/paho.mqtt.c/src/MQTTProtocolOut.c:332: undefined reference to `Proxy_connect'
collect2: error: ld returned 1 exit status
make[3]: *** [serial2mqtt.mk:79: Debug/serial2mqtt] Error 1
make[3]: Leaving directory '/home/build/openwrt/build_dir/target-mipsel_24kc_musl/serial2mqtt-0.0/serial2mqtt'
make[2]: *** [Makefile:58: /home/build/openwrt/build_dir/target-mipsel_24kc_musl/serial2mqtt-0.0/.built] Error 2
make[2]: Leaving directory '/home/build/openwrt/package/serial2mqtt'
time: package/serial2mqtt/compile#4.19#0.35#4.49
    ERROR: package/serial2mqtt failed to build.
make[1]: *** [package/Makefile:116: package/serial2mqtt/compile] Error 1
make[1]: Leaving directory '/home/build/openwrt'
make: *** [/home/build/openwrt/include/toplevel.mk:223: package/serial2mqtt/compile] Error 2
build@db05a3db4285:~/openwrt$

---------------------------------------------

**Comment by RadioOperator** [comment]
This is the new version paho.mqtt.c features, the old version did not have the source file `Proxy.c`.
Prossible solutions:
1. using the old version paho.mqtt.c.
2. add Proxy.c into the compile/link process. refer to my https://github.com/vortex314/serial2mqtt/issues/44#issuecomment-1019433261

**Comment by r32190** [comment]
Thanks.
1. Where is that file?
2. I cannot find any "proxy.c" inside that thread.

**Comment by RadioOperator** [comment]
check the Makefile, the source package paho.mqtt.c is downloaded from github when you compiling.

**Comment by r32190** [comment]
Thanks. My SDK docker crashed, recompiled and found the paho.mqtt.c directory.
How can I use old version?

**Comment by RadioOperator** [comment]
I jsut upload my code, refer to my new repo:
https://github.com/RadioOperator/openwrt-serial2mqtt

**Comment by r32190** [comment]
Thanks. It's got compiled.
